# Generated by Django 3.2 on 2026-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatBookCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=45, verbose_name='IP 地址')),
                ('lang', models.CharField(default='zh', max_length=10, verbose_name='语言')),
                ('response_data', models.TextField(verbose_name='响应 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'IP 信誉缓存',
                'verbose_name_plural': 'IP 信誉缓存',
                'db_table': 'threatbook_cache',
            },
        ),
        migrations.CreateModel(
            name='ThreatBookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '微步配置',
                'verbose_name_plural': '微步配置',
                'db_table': 'threatbook_config',
            },
        ),
        migrations.AddIndex(
            model_name='threatbookcache',
            index=models.Index(fields=['resource', 'lang'], name='threatbook__resourc_a6cfe6_idx'),
        ),
    ]
