# Generated by Django 3.2 on 2026-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day02', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tag',
            field=models.ManyToManyField(to='day02.Tags', verbose_name='标签'),
        ),
    ]
