# Generated by Django 3.2 on 2026-06-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02_权限', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='role',
        ),
    ]
